blog/urls.py
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from config.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', never_cache(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Модель блоговой записи."""
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, **NULLABLE, verbose_name='slug')
    body = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    create_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикаций')
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        """Строковое представление блоговой модели."""
        return f"{self.title} {self.slug} {self.body} {self.count_views}"

    class Meta:
        """Метаданные о модели."""
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Создаёт новую статью."""
    model = Blog
    fields = ('title', 'body', 'image', 'is_published')
    permission_required = 'blog.add_article'
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """
        Преобразует заголовок блога в человекопонятный URL формат.
        Сохраняет в базе данных новый объект модели.
        """
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Обновляет статью."""
    model = Blog
    fields = ('title', 'body', 'image', 'is_published')
    permission_required = 'blog.change_article'
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """
        Преобразует заголовок блога в человекопонятный URL формат.
        Сохраняет в базе данных новый объект модели.
        """
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        """Возвращает на страницу со статьями, после редактирования."""
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(LoginRequiredMixin, ListView):
    """Выводит на экран статьи."""
    model = Blog
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        """Фильтрует статьи по признаку-is_published."""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogDetailView(DetailView):
    """Выводит на экран отдельную статью."""
    model = Blog

    def get_object(self, queryset=None):
        """Увеличивает количество просмотров при каждом открытии статьи."""
        self.object = super().get_object(queryset)
        if self.object:
            self.object.count_views += 1
            self.object.save(update_fields=['count_views'])
        return self.object


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Удаляет статью."""
    model = Blog
    permission_required = 'blog.delete_article'
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью {{ object.title }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Статья '{{ object.title }}' ({{ object.slug }})
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.body }}
                        </p>
                    </div>
                    <div class="col-6">
                        <img src="/media/{{ object.image }}"/>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.count_views }}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a></a>
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <div class="col-12">
                {% if perms.blog.add_article %}
                    <a class='btn btn-primary' href="{% url 'blog:create' %}">Добавить материал</a>
                {% endif %}
            </div>
        </div>
        {% for object in object_list %}
            <div class="p-3 col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.body|truncatechars:50 }}</li>
                        </ul>
                        <div class="btn-group">
                            <a class="p-2 btn btn-outline-success " href="{% url 'blog:view' object.pk %}">view</a>
                            {% if perms.blog.change_article %}
                                <a class="p-2 btn btn-outline-primary" href="{% url 'blog:update' object.pk %}">edit</a>
                            {% endif %}
                            {% if perms.blog.delete_article %}
                                <a class="p-2 btn btn-outline-danger"
                                   href="{% url 'blog:delete' object.pk %}">delete</a>
                            {% endif %}
                        </div>
                        <style>
                            .btn-group a {
                                margin-right: 5px;
                            }
                        </style>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}