blog/urls.py
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from config.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', never_cache(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import HomeListView, ContactsView, CategoryListView, ProductListView, ProductDetailView, \
    ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryDetailView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('pruduct/<int:pk>', ProductListView.as_view(), name='product_list'),
    path('product/view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('<int:pk>/product/edit/', never_cache(ProductUpdateView.as_view()), name='product_edit'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/view/<int:pk>/', CategoryDetailView.as_view(), name='category'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    """Модель товара."""
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=200, verbose_name='описание продукта', **NULLABLE)
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.CharField(max_length=50, verbose_name='категория')
    price = models.FloatField(verbose_name='цена')
    date_creation = models.DateField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    date_modification = models.DateField(auto_now_add=True, verbose_name='дата последнего изменения', **NULLABLE)
    users = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='пользователь'
    )
    is_active = models.BooleanField(default=True, verbose_name='в наличии')

    def __str__(self):
        """Строковое представление модели товара."""
        return f'{self.name} {self.category} {self.price} {self.date_creation}'

    class Meta:
        """Метаданные о модели."""
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('category', 'name', 'date_modification')


class Category(models.Model):
    """Модель категории."""
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=200, verbose_name='описание')

    is_active = models.BooleanField(default=True, verbose_name='в наличии')

    def __str__(self):
        """Строковое представление модели товара."""
        return f'{self.name} {self.description}'

    class Meta:
        """Метаданные о модели."""
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    """Модель Версий."""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='Признак текущей версии', default=False)

    def __str__(self):
        """Строковое представление модели версии."""
        return f'{self.version_name} | {self.version_number}'

    class Meta:
        """Метаданные о модели."""
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

forbidden_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар',)


class StyleFormMixin:
    """
    Миксин для добавления стилей к формам.
    При инициализации формы, добавляет класс 'form-control' к виджетам всех полей.
    """

    def __init__(self, *args, **kwargs):
        """
        Инициализация формы.
        Переопределяет метод __init__ для добавления класса 'form-control' к виджетам всех полей.
        """
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Product."""

    class Meta:
        """Метаданные о модели."""
        model = Product
        exclude = ('users',)

    def clean_name(self):
        """
        Валидация поля name.
        Проверяет, что значение поля name не содержит запрещенные слова.
        Если содержит, генерирует ValidationError с сообщением об ошибке.
        """
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in forbidden_words:
            raise forms.ValidationError(f'Нельзя использовать запрещённые слова {forbidden_words}!')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    """Форма для модели Version."""

    class Meta:
        """Метаданные о модели."""
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView, DetailView

from catalog.apps import CatalogConfig
from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product, Version
from catalog.services import get_categories_cache

app_name = CatalogConfig


class HomeListView(LoginRequiredMixin, ListView):
    """Выводит на экран главную страницу с товарами."""
    model = Product
    template_name = 'catalog/product_list.html'
    extra_context = {'title': 'Главная'}


class ContactsView(LoginRequiredMixin, TemplateView):
    """Выводит на экран страницу с контактными данными."""
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        """Выводит в консоль данные из формы обратной связи."""
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"имя: {name} телефон: ({phone}) сообщение: {message}")
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        """
        Возвращает словарь с контекстными данными,
        для отображения заголовка станицы.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    """Выводит на экран страницу с категориями товаров."""
    model = Category
    template_name = 'catalog/category.html'
    extra_context = {
        'object_list': get_categories_cache(),
        'title': 'Категории'
    }


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = context['object'].pk
        context['products'] = Product.objects.filter(category=pk)
        return context


class ProductListView(LoginRequiredMixin, ListView):
    """Выводит на экран страницу с товарами."""
    template_name = 'catalog/product_list.html'
    model = Product

    def get_queryset(self):
        return super().get_queryset().filter(
            category_id=self.kwargs.get('pk'),
            users=self.request.user
        )

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Продукт категории {category_item.name}'
        return context_data
    # def get_queryset(self):
    #     """
    #     Фильтрует набор запросов и возвращает только
    #     объект с соответствующим идентификатором.
    #     """
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(id=self.kwargs.get('pk'))
    #     return queryset
    #
    # def get_context_data(self, *args, **kwargs):
    #     """
    #     Возвращает словарь с контекстными данными,
    #     для отображения заголовка станицы.
    #     """
    #     context_data = super().get_context_data(*args, **kwargs)
    #     category_item = Category.objects.get(pk=self.kwargs.get('pk'))
    #     context_data['title'] = f'Продукт категории {category_item.name}'
    #
    #     return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Создает новый продукт."""
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        """Обрабатывает валидную форму."""
        self.object = form.save()
        self.object.users = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Обновляет продукт."""
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.update_product'
    success_url = reverse_lazy('catalog:product_view')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.users != self.request.user:
            raise Http404
        return self.object

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного сохранения формы."""
        return reverse('catalog:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        """Возвращает контекст данных для отображения формы."""
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        """Обрабатывает действия при валидной форме."""
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Выводит информацию о продукте."""
    model = Product


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Удаляет продукт."""
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">{{ title }} </h4>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Skystore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">+7123123123</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.description|title|slice:'100' }}</li>
                        </ul>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' object.id %}">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr class="table-info">
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>1234567890</td>
                            </tr>
                            <tr class="table-info">
                                <td class="w-25">Адрес</td>
                                <td>г. Любой, ул. Любая</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщите о проблеме" required></textarea>
                            </div>
                            <button type="submit" class="btn  btn-lg btn-info btn-outline-light">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/product_list.html' %}
{% load my_tags %}
<!doctype html>
<html lang="en">

{% block content %}

    <div class="container">
        <div class="row text-center">
            {% for product in products %}

                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <img class="card-img-top"
                                 src="{{ product.image|my_media }}"
                                 alt="Card image">
                            <h4 class="my-0 font-weight-normal">{{ product.name|title }}

                            </h4>
                        </div>
                        <div class="card-body">
                            <h1 class="fs-4 card-title pricing-card-title">{{ product.price }} руб</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ product.description }}</li>
                            </ul>
                            <a class="p-2 btn btn-outline-primary"
                               href="{% url 'catalog:product' product.id %}">Перейти</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт {{ object.name }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.name }}
                        </h3>
                    </div>
                    <div class="col-6">
                        <img src="/media/{{ object.image }}"/>
                    </div>
                    <div class="card-body">
                        <p>
                            Описание: {{ object.description }}
                        </p>
                    </div>
                    <div class="card-footer h5">
                        Цена: {{ object.price }} рублей
                    </div>
                    <div class="card-footer">
                        <td class="w-25">Пользователь:</td>
                        {{ object.users|default:'Не установлен' }}
                    </div>
                    <div class="card-footer">
                        <td class="w-25">Дата добавления:</td>
                        {{ object.date_creation|default:'-' }}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        {% if not object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Создание продукта
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Создать
                        </button>
                    </div>
                </div>
            </div>
            </form>
        {% endif %}

    <form method="post" class="row" enctype="multipart/form-data">
        {% if object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Редактирование продукта
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Сохранить
                        </button>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версии продукта
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </form>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="row text-center">
        <div class="col-12">
            {% if perms.catalog.add_product %}
                <a class='btn btn-primary mb-5' href="{% url 'catalog:product_create' %}">Добавить продукт</a>
            {% endif %}
        </div>
        {% for object in object_list %}
            <div class="col-md-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top"
                             src="{{ object.image|my_media }}"
                             alt="Card image">
                        <h3 class="card-title pricing-card-title">{{ object.price }} руб</h3>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.description|slice:'100' }}</li>
                        </ul>
                        {% if request.user.is_authenticated %}
                            <div class="btn-group h5 mb-auto">
                            <a class="p-2 btn btn-outline-success "
                               href="{% url 'catalog:product_view' object.pk %}">view</a>
                        {% if perms.catalog.update_product %}
                            <a class="p-2 btn btn-outline-primary "
                               href="{% url 'catalog:product_edit' object.pk %}">update</a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                            <a class="p-2 btn btn-outline-danger "
                               href="{% url 'catalog:product_delete' object.pk %}">delete</a>
                        {% endif %}
                        </div>
                     {% endif %}
                    </div>
                    {% for version in object.version_set.all %}
                        {% if version.is_active %}
                            <div class="card-footer">
                                Номер активной версии: {{ version.version_number }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% if forloop.counter|divisibleby:4 and not forloop.last %}
                </div>
                <div class="row text-center">
            {% endif %}
        {% endfor %}
        </div>

{% endblock %}